language: go

python:
    - master

# before_install
# install - install any dependencies required
install:
    - go get github.com/gohugoio/hugo

# script - run the build script
script:
    - bash publish.sh
